# Generated by Django 3.2.7 on 2021-10-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Untis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Untisdata', models.JSONField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='untisPassword',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='untisUsername',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
