# Generated by Django 3.2.7 on 2021-10-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='snippetID',
            field=models.IntegerField(null=True),
        ),
    ]
