# Generated by Django 3.2.7 on 2021-10-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_snippetid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='snippetID',
        ),
    ]
